# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k.xci
# IP: The module: 'afifo_w8_d4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k.xci
# IP: The module: 'afifo_w8_d4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/afifo_w8_d4k/afifo_w8_d4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_w8_d4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
