# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sfifo_ft_w144_d256/sfifo_ft_w144_d256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sfifo_ft_w144_d256 || ORIG_REF_NAME==sfifo_ft_w144_d256} -quiet] -quiet
