# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k.xci
# IP: The module: 'sfifo_w8_d16k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_w8_d16k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_w8_d16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k.xci
# IP: The module: 'sfifo_w8_d16k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_w8_d16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_w8_d16k/sfifo_w8_d16k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_w8_d16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
