# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sram_w128_d2k/sram_w128_d2k.xci
# IP: The module: 'sram_w128_d2k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sram_w128_d2k/sram_w128_d2k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_w128_d2k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sram_w128_d2k/sram_w128_d2k.xci
# IP: The module: 'sram_w128_d2k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sram_w128_d2k/sram_w128_d2k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram_w128_d2k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
