# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024.xci
# IP: The module: 'sfifo_ft_w14_d1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_ft_w14_d1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_ft_w14_d1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/vivado_project/switch_32/switch_32.srcs/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024.xci
# IP: The module: 'sfifo_ft_w14_d1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_ft_w14_d1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/vivado_project/switch_32/switch_32.gen/sources_1/ip/sfifo_ft_w14_d1024/sfifo_ft_w14_d1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sfifo_ft_w14_d1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
